# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres:14.5
    restart: always
    ports: [5432:5432]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data